version: '3.8'  # Versão explícita para garantir compatibilidade

services:
  postgres:
    image: postgres:alpine
    container_name: postgres_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Volume persistente
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Script de inicialização
    environment:
      POSTGRES_USER: pedro
      POSTGRES_PASSWORD: pedrosenha
    networks:
      - webnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pedro"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  app:
    build: .
    container_name: app
    ports:
      - "8002:8002"
    environment:
      DOCKER_ENV: 'true'
    networks:
      - webnet
    depends_on:
      postgres:
        condition: service_healthy
      prometheus:
        condition: service_started
    command: ['sh', '/usr/src/app/commands.sh']
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter_app
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - webnet
    pid: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_app
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Configuração do Prometheus
    ports:
      - "9090:9090"
    networks:
      - webnet
    restart: unless-stopped  # Adicionado para garantir resilência

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_app
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana  # Volume persistente para dados do Grafana
    depends_on:
      - prometheus
    networks:
      - webnet
    restart: unless-stopped

# --- Definições de Redes e Volumes ---
networks:
  webnet:
    driver: bridge  # Explícito (opcional, mas recomendado)

volumes:
  pgdata:  # Volume para PostgreSQL
  grafana-storage:  # Volume para Grafana (adicionado)
