global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app-1'
    static_configs:
      - targets: ['app1:8006']

  - job_name: 'app-2'
    static_configs:
      - targets: ['app2:8005']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

