global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app-prom'
    static_configs:
      - targets: ['app:8002']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

