# Generated by Django 5.1.5 on 2025-06-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aerotur', '0002_pessoa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
